### ISSUE TITLE
Local variable 'image' is assigned to but never used

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.timeline#1]
o tile do timeline inclui o [seguinte código](https://github.com/plonegovbr/brasil.gov.timeline/blob/master/src/brasil/gov/timeline/tiles/timeline.py#L147):

```python
def get_image(self, item):
    if item:
        # FIXME: local variable 'image' is assigned to but never used
        image = item.image_timeline  # noqa: F841
        scales = item.restrictedTraverse('@@images')
        scale = scales.scale('image_timeline', scale='timeline_view')
        return scale
```

aparentemente isso é um bug do código original.

**Comment by hvelarde** [comment]
@almeidajeff preciso de seu esclarecimento aqui.

**Comment by almeidajeff** [comment]
@hvelarde devo ter criado esta variável por algum motivo que não se torna mais necessário.

Ao ver pode removê-la sem problemas.
